services:
  - type: web
    name: blog-backend
    runtime: python
    rootDir: back
    buildCommand: pip install -r requirements.txt && python build.sh
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///blog.db
      - key: PYTHON_VERSION
        value: 3.9.5
